### ISSUE TITLE
TypeError for Dropdown menu

### ISSUE THREAD

**Issue by FlyinTeller** [Daniel-van-der-Poel/The-Clean-Sheet#3]
Hi Daniel,

thank you for this great sheet, realy a time saver when creating a new character. I have been having this issue with the "Add Items & Spells" opion however. Turning on the javascript console gives me this:

TypeError: tempSpell is undefined
2773:Document-Level:functions
TypeError: second argument to Function.prototype.apply must be an array
1983:Document-Level:functions
TypeError: second argument to Function.prototype.apply must be an array
1983:Document-Level:functions
TypeError: second argument to Function.prototype.apply must be an array
1983:Document-Level:functions

I am using "Adobe Acrobat Reader DC" Version 2019.012.20040 on both a Windows 8 and 10 machine. Have you ever seen this issue and know a quick fix?

Cheers,
Flo

P.S. This is a copy of the previously closed issue, which I accidentaly sent with the wrong account

**Comment by Daniel-van-der-Poel** [comment]
Hi Flo,

Glad to hear the sheet is helping you. 

Unfortunately I no longer have access to Acrobat Pro, so I'm afraid I can't fix the bug myself. I'll leave this issue open for now.

I've added an older version, 2.5, to the repository. There's a small change it doesn't have the bug..

Cheers,

Daniël

**Comment by FlyinTeller** [comment]
Hi Daniel,

thank you for the reply, I have created a fork and actually found a fix. I have no real clue of Javascript, but something about accessing arrays must have changed. In my version, the spells are working again, but I will also check out your other version

**Comment by Daniel-van-der-Poel** [comment]
Thanks a lot; I merged your fix.
